### ISSUE TITLE
error: invalid_client

### ISSUE THREAD

**Issue by elitistphoenix** [Parrot-Developers/node-flower-bridge#10]
I changed credentials.json to add
"url": "https://api-flower-power-pot.parrot.com"

Now it ends up with:
  url: 'https://api-flower-power-pot.parrot.com/user/v3/authenticate',
  method: 'POST' }
CODE: 400
error: invalid_client

The master branch works but doesn't sync properly.

**Comment by danielbh** [comment]
+1

**Comment by danielbh** [comment]
Fixed this by signing up for a new API key with the same account register info.

**Comment by danielbh** [comment]
Also I just noticed u are using v3. you should use v1

GET https://api-flower-power-pot.parrot.com/user/v1/authenticate

**Comment by bsautron** [comment]
Hi guys,

try to checkout to 'pot' branch:
> git checkout fetch
> git checkout pot
> npm install

This branch is experimental but it is compatible with the Parrot Pot and Flower Powers (firmware 2)

**Comment by danielbh** [comment]
@bsautron yes that worked for me too.

**Comment by elitistphoenix** [comment]
@bsautron I got a fresh copy of the Pots branch and changed the credentials file and it didn't seem to work.
pi@raspberrypi ~/node-flower-bridge-pot $ ./bridge display

-- Flower Bridge --

✔ Login!
[Jan 11 2017 17:09:54]: New process every 15 minutes

(Then nothing... for 2 hours)

**Comment by Charlyphyro** [comment]
Can someone explain this in a step by step guide, for dummies :)

**Comment by pbranly** [comment]
Hi 
I have the same issue
It connects but no message back in debug mode I have

**Comment by pbranly** [comment]
Sorry for e empty message
The message is error in GetInformationsCloud
And I am too much dummy to know how to get the pot branch
If i try the make sudo npm install xxxx/pot, i get a lot of errors 
Please help
Regards
Philippe
