### ISSUE TITLE
Parrot cloud and api no more supported 

### ISSUE THREAD

**Issue by jacopomarcovaldi** [Parrot-Developers/node-flower-bridge#12]
Hi,
parrot doesn't support cloud data for Flower power, so i am wondering if you can update this project and let it save data on a local db (on the raspberry in my case).
thank you.
Jacopo

**Comment by cbensahlatani** [comment]
Hi,
Parrot has changed server but all the data have been transfered to the new server (if you updated the app on your phone and made the import). You can retrieve it on the new server (URL has been changed in this repo, just pull the master branch).

BR,
Céline

**Comment by jacopomarcovaldi** [comment]
thank you for your reply.
I will try to pull the master branch :)

**Comment by jacopomarcovaldi** [comment]
Ok, i pull the master branch and execute install.sh (i moved old folder in a temp diretcory), copy the old credential.json and when i run ./bridge display i got this error:

                                                                                                                         
-- Flower Bridge --                                                                                                      
                                                                                                                         
[---] No program is running                                                                                              
node /home/pi/node-flower-bridge/start.js                                                                                
POST/urlencoded /user/v3/authenticate                                                                                    
client_id: [MYCLIENTID]                                                                                 
client_secret: [MYSECRET]                                                          
username: [MYUSERNAME]                                                                                  
password: [MYPASSWORD]                                                                                                       
grant_type: password                                                                                                     
app_identifier:                                                                                                          
{ headers:                                                                                                               
   { 'Content-Type': 'application/x-www-form-urlencoded',                                                                
     Authorization: '' },                                                                                                
  body: 'client_id=[MYCLIENTID]&client_secret=[MYSECRET]&usernam
e=[MYUSERNAME]&password=[MYPASSWORD]&grant_type=password&app_identifier=',                                
  url: 'undefined/user/v3/authenticate',                                                                                 
  method: 'POST' }                                                                                                       
Error: Invalid URI "undefined/user/v3/authenticate"

Can you help me?

Thank you :)

**Comment by cbensahlatani** [comment]
Hi,
Server  has changed so you need new key. 
This is explained in the tutorial : http://developer.parrot.com/docs/FlowerPower/

New url to get one is https://api-flower-power-pot.parrot.com/api_access/signup

Céline

**Comment by jacopomarcovaldi** [comment]
Thank you.

**Comment by Netfreak25** [comment]
had the same issue, new key, plus adding the uri line to the credentials.json helped

**Comment by jacopomarcovaldi** [comment]
Thank you

**Comment by jacopomarcovaldi** [comment]
I am sorry but now i receive this response: 8010: Incorrect email and/or password  
I registered my email on an new api url and i received an email with the secret code but i didn't receive an email with a confirmation url.
Can you help me?
Thank you.

**Comment by cbensahlatani** [comment]
Mmm sorry ? What do you mean by confirmation URL ?
" I registered my email on an new api url " > how ? and what do you mean by that ?

The email you received contained Access code  : youremail
Secret access : a key
These are server credentials, and then you have user email and pass, it seems that they are wrong.
Try to use the mobile application to login with it, you'll know if they are wrong or not. You can also reset it using the app.

**Comment by jacopomarcovaldi** [comment]
Hi,
i am sorry but it's hard for me to write in english :) 
When you told me that parrot has changed api url and for this reason i had to register again i thought that they will send me also a new username and a new password.
I am sure that my username and my password are correct and for these reason i don't understand why a receive this response.
This evening i will try to reset my password with the app.
Thank you for your help :)

**Comment by cbensahlatani** [comment]
Let's make it clear.
To make request on a server you have to use clients keys. To make request that are related to a user you need to authenticate with this user's credential.

Before, we used server A. So you had a client key pair related to server A and you had a user on this server A.

Now, we changed server to server B. So to request sthg to it, you need new pair of clients key (you got it with the URL I gave you) but you also need to authenticate to the user on this new server. The accounts have not been automatically transferred to server B because lots of it are not used anymore. If you used the new application (released in August), an import of your data has been made. If you did not, then you don't have an account on server B. In that case you need to make a new one because we deactivated server A in end of March.

**Comment by jacopomarcovaldi** [comment]
Hi, yesterday i figured out why i was so confused: google playstore on my android tablet says that the app was updated but it wasn't! I try unistalling and reinstalling it but the app on my tablet was always the old one! Yesterday i downloaded the new apk and installed it and now it works.
I am sorry if i waste your time.
Thank you for your help :)

**Comment by JOHNEPPILLAR** [comment]
Hi, I am unable to register for a new api key.

https://apiflowerpower.parrot.com/api_access/signup
Does not have any website behind it and

https://api-flower-power-pot.parrot.com/api_access/signup
Gives me the error "We're sorry, but something went wrong."

Thanks

**Comment by wackoracoon** [comment]
Hello, 
Still the same error when I try to register "We're sorry, but something went wrong."
Do you close registration ?
Thanks

**Comment by nervalo88** [comment]
Same issue there ! Please support

**Comment by mathisFasolo** [comment]
I have got the same issue on parrot api registration website : "We're sorry, but something went wrong."
I need this credential for a university project
Thanks for providing a support 
Regards 
M.Fasolo

**Comment by viotemp1** [comment]
Anybody figure out this We're sorry, but something went wrong."?

**Comment by danielbh** [comment]
It works. Just sign up and use your parrot username and password and the api credentials they send you in the e-mail.

**Comment by nervalo88** [comment]
yep, it works! Seems something was fixed.
For Gmail addresses, don't forget to check your spam folder.

**Comment by wackoracoon** [comment]
Thanks it works again ! 
For my yahoo address it was also in my spam folder.

**Comment by reetpetite** [comment]
Unfortunately for me node-flower-bridge does not work properly. I assume it has something to do with the new API. I changed some paths in FlowerPowerCloud.js. When I run `./bridge display` with DEBUG turned on I can see a successful login. Then the debug messages from `GET/json /garden/v1/status` then from `GET/json /garden/v2/configuration` and finally from `GET/json /user/v4/profile` they all say `body: 'null',`.
The last line is `[]` and then nothing happens.

Here's the bit I changed in FlowerPowerCloud.js:

``` 	var api = {

		// Profile
		'getProfile': {method: 'GET/json', path: '/user/v4/profile', auth: true},
		'getUserVersions': {method: 'GET/json', path: '/user/v1/versions', auth: true},
		'verify': {method: 'GET/json', path: '/user/v1/verify', auth: true},

		// Garden
		//old 'getSyncGarden': {method: 'GET/json', path: '/sensor_data/v4/garden_locations_status', auth: true},
		'getSyncGarden': {method: 'GET/json', path: '/garden/v1/status', auth: true},
		'sendSamples': {method: 'PUT/json', path: '/sensor_data/v8/sample', auth: true},
		//old 'getSyncData': {method: 'GET/json', path: '/sensor_data/v3/sync', auth: true},
		'getSyncData': {method: 'GET/json', path: '/garden/v2/configuration', auth: true},
		'getFirmwareUpdate': {method: 'GET/json', path: '/sensor_data/v1/firmware_update', auth: true},
		//old 'getLocationSamples': {method: 'GET/json', path: '/sensor_data/v2/sample/location/:location_identifier', auth: true},
		'getLocationSamples': {method: 'GET/json', path: '/sensor_data/v6/sample/location/:location_identifier', auth: true},
		'getStatistics': {method: 'GET/json', path: '/sensor_data/v1/statistics/:location_identifier', auth: true},

		// Images
		'getImageLocation': {method: 'GET/json', path: '/image/v3/location/user_images/:location_identifier', auth: true},
	};
```

Your help is highly appreciated.
