### ISSUE TITLE
Do not package needless stuff (reduce the unpacked size more than 1000 times)

### ISSUE THREAD

**Issue by ChALkeR** [Parrot-Developers/node-flower-bridge#2]
_Disclaimer: I do not use the package, this was found during automated npm packages downloading._

Atm, your npm package `node-flower-bridge@1.8.4` has packaged size **153 MiB**, and installed size **154 MiB**.

**154 MiB** (99.906%) of that is consumed by `nexus-installer-3.0.0-m6-unix-archive.tar.gz` and `nexus-installer-3.0.0-m6-unix-archive.tar.gz.1` files.

I suspect that those files was accidently packaged.

You could add those to `.npmignore` (if you have an `.npmignore` already) or to `.gitignore` (if you don't have an `.npmignore`).

---

Your current package files (as of `node-flower-bridge@1.8.4`):

```
node-flower-bridge-1.8.4.tgz
├── bridge
├── caca.js
├── credentials.json
├── database
│   └── process.db
├── deamon.sh
├── index.js
├── .jshintrc
├── lib
│   ├── FlowerBridge.js
│   ├── helpers.js
│   ├── SyncFP.js
│   └── TaskFP.js
├── LICENSE
├── nexus-installer-3.0.0-m6-unix-archive.tar.gz
├── nexus-installer-3.0.0-m6-unix-archive.tar.gz.1
├── node-flower-power
│   ├── flower-power.txt
│   ├── index.js
│   ├── LICENSE
│   ├── .npmignore
│   ├── package.json
│   ├── pseudo.js
│   ├── README.md
│   ├── services.js
│   ├── test.js
│   ├── TSRP
│   │   ├── flower-power.rc
│   │   ├── flower-power-tsrp.js
│   │   └── README.md
│   ├── Update.js
│   ├── UploadBuffer.js
│   └── Upload.js
├── node-flower-power-cloud
│   ├── ApiError.js
│   ├── FlowerPowerCloud.js
│   ├── LICENSE
│   ├── .npmignore
│   ├── package.json
│   ├── README.md
│   └── test.js
├── package.json
├── priority.js
├── README.md
├── start.js
├── test.js
├── trace.log
├── .travis.yml
└── updatedb

5 directories, 44 files
```

**Comment by bsautron** [comment]
hi @ChALkeR, thanks.

I remove them and add a `.gitignore`: https://github.com/Parrot-Developers/node-flower-bridge/commit/6479f0a56377810c0c9c8ac2b9dcb739e70b84a5
