### ISSUE TITLE
problem in raspi

### ISSUE THREAD

**Issue by fildy** [Parrot-Developers/node-flower-bridge#3]
Hi,
i try to install in raspi. ble ok, node ok.
when I run the bridge display it shows this

-- Flower Bridge --

module.js:341
    throw err;
    ^

Error: Cannot find module 'bluetooth-hci-socket'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/pi/Downloads/node-flower-bridge-master/node_modules/noble/lib/hci-socket/hci.js:6:26)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

is there something that I miss?

**Comment by RalphPungaKronbergs** [comment]
Did 'sudo hciconfig hci0 up' work fine?

**Comment by fildy** [comment]
sudo hciconfig hci0 up
nothing shows

sudo hciconfig
hci0:   Type: BR/EDR  Bus: USB
        BD Address: 5C:F3:70:70:54:93  ACL MTU: 1021:8  SCO MTU: 64:1
        UP RUNNING
        RX bytes:616 acl:0 sco:0 events:34 errors:0
        TX bytes:380 acl:0 sco:0 commands:34 errors:0

is it normal?

**Comment by RalphPungaKronbergs** [comment]
That all looks good.

Did you ran into any error messages while installing
node-flower-bridge?

Am 13.02.2016 um 11:26 schrieb fildy:

> sudo hciconfig hci0 up
> nothing shows
> 
> sudo hciconfig
> hci0: Type: BR/EDR Bus: USB
> BD Address: 5C:F3:70:70:54:93 ACL MTU: 1021:8 SCO MTU: 64:1
> UP RUNNING
> RX bytes:616 acl:0 sco:0 events:34 errors:0
> TX bytes:380 acl:0 sco:0 commands:34 errors:0
> 
> is it normal?
> 
> On Fri, Feb 12, 2016 at 8:54 PM, Ralph Punga-Kronbergs <

**Comment by fildy** [comment]
No error.

**Comment by RalphPungaKronbergs** [comment]
What distri are you using?

It's working fine with Jessie here...

Am 14.02.2016 um 07:43 schrieb fildy:

> No error.
> 
> On Sat, 13 Feb 2016 at 21:33, Ralph Punga-Kronbergs <

**Comment by fildy** [comment]
I'm using jessi too
I have 2 flower power and recognized with ble.

**Comment by bsautron** [comment]
Hi, what is the your raspi model?
https://github.com/sandeepmistry/noble/issues/253

**Comment by mbuffat** [comment]
using a raspberry B+, I had the same problem
It is related to the version of nodejs. You have to install the right nodejs for the B+ and not the nodejs for new raspberry pi 2
with node_latest_armhf.deb on jessie 
it works (but not with the version found on nodesource)

**Comment by fildy** [comment]
I'm using Raspberry Pi 2 Model B .
