### ISSUE TITLE
Current stable and future-proof branch?

### ISSUE THREAD

**Issue by RalphPungaKronbergs** [Parrot-Developers/node-flower-bridge#5]
Hi,

what's the most recent stable and future-proof branch to clone best? Master or v2?

Cheers
Ralph

**Comment by bsautron** [comment]
Hi,

The v2 branch is reserved for the new products and a new server of parrot, but not available for public today.
Refer the last version in the master branch.

Bruno

**Comment by RalphPungaKronbergs** [comment]
Hi Bruno,

thanks for clarifying. New parrot products and server? That sounds interesting! Is there any information available about this?

Cheers,
Ralph

**Comment by bsautron** [comment]
[Parrot pot](https://www.youtube.com/watch?v=Zpjl2KP8fiQ)
Soon! :+1:
